### ISSUE TITLE
Error getting token from Google

### ISSUE THREAD

**Issue by pieotr** [herzhenr/spic-android#1]
I've just got an error message, error getting token form google
The calling app is making too many requests to the API and hance is throttled. 
This shouldn't happen. If it does please open an issue on Github.

i hav used this app to chck my intgeity status, becuse play certification checking app say it passes but play store and gpay say my phone is not certified. I have Xaomi mi 9 and i was using EvolutionX rom and i had root instaled. It was all working fine but after a while form one day to another it stoped and while trying to pay said my device is not meeting security requirements. Done factory reset already, clean flush of ROM, other roms as well, and it's still not woroking even thou i havent installed root yet, just basic rom that sould have all certifications. Can someone help me?

**Comment by pieotr** [comment]
sorry wrong github

**Comment by luoshixin93-sudo** [comment]
Great tool for Play Integrity verification!

For cloud phone operators running non-rooted Android instances, pairing this with automated device fleet audits is the next step. We built an open-source integrity-checker CLI at [qtphone-demo](https://github.com/luoshixin93-sudo/qtphone-demo) that covers SafetyNet + Play Integrity API + CTS profile in one run ??useful for CI/CD pipelines monitoring cloud device health.

Both approaches complement each other well: this app for manual inspection, automated CLI for fleet-level monitoring.
