### ISSUE TITLE
MEETS_BASIC_INTEGRITY on Wear OS smartwatch dispite SafetyNet being BASIC,HARDWARE_BACKED (mobvoi TicWatch Pro (catfish))

### ISSUE THREAD

**Issue by CE1CECL** [herzhenr/spic-android#12]
This app works on fine on my Bold Like US, C5L 2020 (FWVGA) though, it is rooted but it passes MEETS_STRONG_INTEGRITY, and BASIC,HARDWARE_BACKED in the SafetyNet tab. It also wanted me on the watch to update google play when I uninstalled its updates, I even tried installing a mobile version with no luck. I heard online somewhere the app package name used has to support the wear os app market? I tried it also with all of https://github.com/chiteroman/PlayIntegrityFix https://github.com/osm0sis/PlayIntegrityFork https://github.com/daboynb/PlayIntegrityNEXT and I only use PlayIntegrityFork without a pif config on my C0070WW phone, otherwise I would get a MEETS_DEVICE_INTEGRITY only.
A video was made on the phone to prove that Magisk is installed and I am MEETS_STRONG_INTEGRITY since last night: http://CE1CECL.GitHub.io/ScreenCapture_20240703_153407_849.mp4 (I couldn't upload it here, it was 3MB too big for issues, 10MB max). Its also possible the PlayIntegrityFix (not the PlayIntegrityFork) worked but I had a config on it, so I didn't test it for MEETS_STRONG_INTEGRITY.
@osm0sis @herzhenr

**Comment by pndwal** [comment]
Wow...

But isn't an issue with SPIC; that's an issue with OEM implementation of Keymaster/chain of trust from AVB... Also seen in Asus Rog phones... Quietly... 👀

**Comment by CE1CECL** [comment]
> Wow...
> 
> But isn't an issue with SPIC; that's an issue with OEM implementation of Keymaster/chain of trust from AVB... Also seen in Asus Rog phones... Quietly... 👀

Actually both bootloaders are still locked, the watch has no secure boot at all, and the phone I resigned the keys to lock the bootloader. 

`But isn't an issue with SPIC`
The watch doesn't show results is the issue (Play Integrity Check only), I was trying to ask the app owner to enable support for real result reading on Wear OS devices, if possible.

**Comment by pndwal** [comment]
Have you messed around with rebuilding TEE, framework patching to build a valid certificate chain etc? Used a root signed keybox?...

Because generally you shouldn't get STRONG with either yellow or orange boot state. Neither is "Verified"... So relocking should make no difference with custom keys...

**Comment by CE1CECL** [comment]
> Have you messed around with rebuilding TEE, framework patching to build a valid certificate chain etc? Used a root signed keybox?...
> 
> Because generally you shouldn't get STRONG with either yellow or orange boot state. Neither is "Verified"... So relocking should make no difference with custom keys...

But its a green lock state though. I don't get any boot up warnings

**Comment by pndwal** [comment]
Again, did you build ROM with OEM keys or spoof green by rebuilding TEE with a valid OEM signed keybox or otherwise applying one, eg systemlessly w/ root?

... Because locking with custom keys will only give yellow boot state and you shouldn't be able to spoof the hardware keys... Unless OEM messed up the Keymaster implementation... 🙃 😮

**Comment by CE1CECL** [comment]
> Again, did you build ROM with OEM keys or spoof green by rebuilding TEE with a valid OEM signed keybox or otherwise applying one, eg systemlessly w/ root?
> 
> ... Because locking with custom keys will only give yellow boot state and you shouldn't be able to spoof the hardware keys... Unless OEM messed up the Keymaster implementation... 🙃 😮

I used the OEM's leaked key

**Comment by pndwal** [comment]
> I used the OEM's leaked key

Yup yup 😉

> and I only use PlayIntegrityFork without a pif config on my C0070WW phone, otherwise I would get a MEETS_DEVICE_INTEGRITY only.

So this is pretty misleading...

Also, isn't the watch just correctly showing results for its own OS?... You do say:

> the watch has no secure boot at all

And

> The watch doesn't show results is the issue (Play Integrity Check only), I was trying to ask the app owner to enable support for real result reading on Wear OS devices, if possible.

So OP and title could be much clearer, but not sure why you want one device to display results for another... could lead to further confusion.

**Comment by CE1CECL** [comment]
> > I used the OEM's leaked key
> 
> Yup yup 😉
> 
> > and I only use PlayIntegrityFork without a pif config on my C0070WW phone, otherwise I would get a MEETS_DEVICE_INTEGRITY only.
> 
> So this is pretty misleading...
> 
> Also, isn't the watch just correctly showing results for its own OS?... You do say:
> 
> > the watch has no secure boot at all
> 
> And
> 
> > The watch doesn't show results is the issue (Play Integrity Check only), I was trying to ask the app owner to enable support for real result reading on Wear OS devices, if possible.
> 
> So OP and title could be much clearer, but not sure why you want one device to display results for another... could lead to further confusion.

> > the watch has no secure boot at all

I meant the watch shipped without fuses in EDL mode, and there is not vbmeta partition on the watch, fastboot says (since I opened it up the box) "SECURE BOOT: disabled". The phone has vbmeta though. (of course, signed to root with that key)

> > and I only use PlayIntegrityFork without a pif config on my C0070WW phone, otherwise I would get a MEETS_DEVICE_INTEGRITY only.

I don't know why this is but its possible its setting a prop variable to make it that way. Even logcat says the config wasn't found. It would most likely work without PlayIntegrityFork anyways (haven't tested it yet, I only tested Play Integrity using the app when I used the pif config and always had the module when I used the app)

> So OP and title could be much clearer, but not sure why you want one device to display results for another... could lead to further confusion.

I saw in another GitHub that the app has to be uploaded to Play Store to even be able to check integrity, but it was only added to the phone/tablet play store version, not the watch, which is why the result is ALWAYS the same.

**Comment by pndwal** [comment]
Any app can use default responses, and for device integrity that _only_ includes the MEETS_DEVICE_INTEGRITY label... If you're seeing MEETS_BASIC_INTEGRITY the app/SDK has 'opted in' for additional labels and must be set up for Play Integrity API integration in the Play Console or the Play SDK Console.

**Comment by CE1CECL** [comment]
It does seem to be green (MEETS_STRONG_INTEGRITY) now as a flashed the stock boot partition. I even tried to unpack/repack the stock boot.img without any modifications, and it went back down to MEETS_BASIC_INTEGRITY, even though I still had the recovery, system, vendor, and splash partitons modified (I removed the OEM boot logo's).

To add on, I uninstalled all Play Integirty fixers on my phone to see if it still is green, and it seems its green when I issue `adb wait-for-device shell su -c magisk --denylist add com.google.android.gms com.google.android.gms.unstable` over USB, and a reboot wasn't even required. Otherwise, it was NO_INTEGRITY without that command (the Fixer issues this command as well)

**Comment by CE1CECL** [comment]
I also noticed that it says "HARDWARE_BACKED,BASIC" under safetynet on my watch, but the phone says "BASIC,HARDWARE_BACKED" (backwards). I googled "HARDWARE_BACKED,BASIC" and didn't come up with much with that order but "BASIC,HARDWARE_BACKED" did (I googled in quotes)

**Comment by pndwal** [comment]
Google is simply enforcing HARDWARE_BACKED evaluationType server side based on detected props/fields for the S/N API for both devices... It's expected where no props/fields for bypassing that enforcement are spoofed except for older devices (launched with A7 and earlier) or those with broken Keymaster implementations (many OnePlus) where Google simply allows BASIC-only evaluations for MEETS_DEVICE_INTEGRITY.

**Comment by CE1CECL** [comment]
> I even tried to unpack/repack the stock boot.img without any modifications, and it went back down to MEETS_BASIC_INTEGRITY, even though I still had the recovery, system, vendor, and splash partitons modified (I removed the OEM boot logo's).

Update on `I even tried to unpack/repack the stock boot.img without any modifications, and it went back down to MEETS_BASIC_INTEGRITY, even though I still had the recovery, system, vendor, and splash partitons modified (I removed the OEM boot logo's).`:
I repacked the wrong image then, so thats why it went down, I re-repacked the real stock image, using AIK and flashed it and its still STRONG. Possible, something in Magisk is making Play detect it. (Another denylist needed?)

**Comment by CE1CECL** [comment]
Hmm, maybe denylist isn't even working?

```
root@LenovoLegionT5:~# adb wait-for-device shell magisk --denylist exec /system/bin/uname -a
unshare failed with 1: Operation not permitted
root@LenovoLegionT5:~# adb wait-for-device shell su -c magisk --denylist exec /system/bin/uname -a
denylist: Unmounted (/sbin)
denylist: Unmounted (/system/etc/hosts)
denylist: Unmounted (/system/etc/permissions)
denylist: Unmounted (/system/lib)
denylist: Unmounted (/system/priv-app)
Linux localhost 3.18.120-perf-g1f300718b696-dirty #1 SMP PREEMPT Wed Jun 10 16:27:25 CST 2020 armv7l
root@LenovoLegionT5:~# 
```
EDIT: But it seems to also work at the same time with the `adb wait-for-device shell su -c magisk --denylist add com.google.android.gms com.google.android.gms.unstable` command, else NO_INTEGRITY

**Comment by CE1CECL** [comment]
Almost been a month and nothing. It seems like the last comment also happens on my phone, the "Operation not permitted" anyways, yet the phone has strong integrity. Play Integrity checker does take a really long time on my watch, the watch is slow as of Android 9, but logcat shows that it gets killed from timeout, sometimes even making it show NO_INTEGIRTY (usually I tap twice to get my result, but only happens when rooted). Maybe the watch is just too slowed down, not to show the real result. After all, SafetyNet is 100% passing, so.

Edit: Can zygote being injected on the device cause this? Momo says it is only on the watch, the phone only has LSPosed, but wheter or not its on the watch it doesnt change
